name = input("What is your name ? ")
age = int(input("How old are you ? "))
residence = input("Where do you live ? ")
print(f"Hello , {name}")
print(f"Your age is {age}")
print(f"I live in {residence}")