a = int(input("Enter a number1 "))
b = int(input("Enter a number2 "))
print(f"The sum of {a} and {b} is",a + b)
print(f"The subtraction of {a} and {b} is",a - b)
print(f"The multiplication of {a} and {b} is",a * b)
print(f"The division of {a} and {b} is",a / b)
print(f"The exponentiation of {a} and {b} is",a ** b)